spring.application.name=spring-security-jwt

spring.profiles.active=${APP_PROFILE:test}

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

# App Properties
omarcosallan.app.jwtSecret= ======================OMarcosAllan=Spring===========================
